name: Backend Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update && sudo apt-get install -y docker-compose
    - name: Start Backend & DB
      run: |
        docker compose -f database/docker-compose.test.yml up --build -d
    - name: Wait for Services
      run: sleep 10  # Wait until database and backend are up and running...
    - name: Execute API Tests
      run: |
        cd service/backend
        go test -v ./tests/...
