name: Backend Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: githubclone
        ports:
          - "5432:5432"

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Go installieren
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Abhängigkeiten installieren
      run: |
        cd service/backend
        go mod tidy

    - name: Tests ausführen
      run: |
        cd service/backend
        go test ./tests/...